apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant1
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: tenant1
  url: ssh://git@github.com/swapnachagam/flux-tenant