apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant1
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: true
  serviceAccountName: tenant1
  sourceRef:
    kind: GitRepository
    name: tenant1
  validation: client